# Generated by Django 5.2.1 on 2025-09-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='price_at_added',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
