# Generated by Django 5.2.1 on 2025-08-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('manager', 'Restaurant Manager'), ('delivery', 'Delivery Person')], default='customer', max_length=20),
        ),
    ]
