# Generated by Django 5.2.1 on 2025-09-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='note',
            field=models.TextField(default='...'),
        ),
    ]
