# Generated by Django 5.2.1 on 2025-09-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reservations_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='data',
            new_name='date',
        ),
    ]
